#ifndef CLDM_ASSERT_H
#define CLDM_ASSERT_H

#include "cldm_macro.h"

#define cldm_assert_trigger(condition, ...) \
    do {                                    \
        if(!(condition)) {                  \
            fprintf(stderr, __VA_ARGS__);   \
            _Exit(1);                       \
        }                                   \
    } while (0)

#define cldm_assert_no_msg(condition)   \
    cldm_assert_trigger(condition, "%s:%d assertion '%s' failed\n", __FILE__, __LINE__, #condition)

#define cldm_assert_msg(condition, msg) \
    cldm_assert_trigger(condition, "%s:%d assertion '%s' failed: " msg "\n", __FILE__, __LINE__, #condition)

#define cldm_assert_variadic(condition, fmt, ...)   \
    cldm_assert_trigger(condition, "%s:%d assertion '%s' failed: " fmt "\n", __FILE__, __LINE__, #condition, __VA_ARGS__)

#define cldm_assert(...)    \
    cldm_overload(cldm_assert, __VA_ARGS__)


#define cldm_assert1(...)   cldm_assert_no_msg(__VA_ARGS__)
#define cldm_assert2(...)   cldm_assert_msg(__VA_ARGS__)
#define cldm_assert3(...)   cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert4(...)   cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert5(...)   cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert6(...)   cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert7(...)   cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert8(...)   cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert9(...)   cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert10(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert11(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert12(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert13(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert14(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert15(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert16(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert17(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert18(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert19(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert20(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert21(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert22(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert23(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert24(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert25(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert26(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert27(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert28(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert29(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert30(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert31(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert32(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert33(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert34(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert35(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert36(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert37(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert38(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert39(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert40(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert41(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert42(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert43(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert44(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert45(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert46(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert47(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert48(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert49(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert50(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert51(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert52(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert53(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert54(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert55(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert56(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert57(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert58(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert59(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert60(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert61(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert62(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert63(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert64(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert65(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert66(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert67(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert68(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert69(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert70(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert71(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert72(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert73(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert74(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert75(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert76(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert77(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert78(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert79(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert80(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert81(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert82(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert83(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert84(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert85(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert86(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert87(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert88(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert89(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert90(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert91(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert92(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert93(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert94(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert95(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert96(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert97(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert98(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert99(...)  cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert100(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert101(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert102(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert103(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert104(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert105(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert106(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert107(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert108(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert109(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert110(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert111(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert112(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert113(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert114(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert115(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert116(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert117(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert118(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert119(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert120(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert121(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert122(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert123(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert124(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert125(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert126(...) cldm_assert_variadic(__VA_ARGS__)
#define cldm_assert127(...) cldm_assert_variadic(__VA_ARGS__)


#endif /* CLDM_ASSERT_H */
